[package]
name          = "amq-protocol-types"
version       = "0.2.2"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP specifications - types"
repository    = "https://github.com/Keruspe/amq-protocol"
documentation = "https://docs.rs/amq-protocol-types"
keywords      = ["amqp","rabbitmq","protocol"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"

[lib]
name = "amq_protocol_types"

[dependencies]
serde        = "^0.9.11"
serde_derive = "^0.9.11"

[badges]
travis-ci = { repository = "Keruspe/amq-protocol" }
