[package]
name          = "amq-protocol-types"
version       = "7.0.0-beta.1" # remember to update html_root_url
edition       = "2021"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP specifications - types"
repository    = "https://github.com/CleverCloud/amq-protocol"
documentation = "https://docs.rs/amq-protocol-types"
keywords      = ["amqp","rabbitmq","protocol","nom"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"
rust-version  = "1.56.0"

[lib]
name = "amq_protocol_types"

[features]
verbose-errors = []

[dependencies]
serde_json = "^1.0"

[dependencies.cookie-factory]
version  = "^0.3"
features = ["std"]

[dependencies.nom]
version  = "^7.0"
features = ["std"]

[dependencies.serde]
version  = "^1.0"
features = ["derive"]

[badges]
travis-ci = { repository = "sozu-proxy/amq-protocol" }
appveyor  = { repository = "Keruspe/amq-protocol" }
