[package]
name          = "amq-protocol-codegen"
version       = "0.1.1"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP specifications - codegen"
repository    = "https://github.com/Keruspe/amq-protocol"
documentation = "https://docs.rs/amq_protocol"
keywords      = ["amqp","rabbitmq","protocol"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"

[lib]
name = "amq_protocol_codegen"

[dependencies]
handlebars   = "^0.25.1"
itertools    = "^0.5.9"
serde        = "^0.9.10"
serde_derive = "^0.9.10"
serde_json   = "^0.9.8"

[badges]
travis-ci = { repository = "Keruspe/amq-protocol" }
