[package]
name          = "amq-protocol-codegen"
version       = "0.10.0"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP specifications - codegen"
repository    = "https://github.com/Keruspe/amq-protocol"
documentation = "https://docs.rs/amq-protocol-codegen"
keywords      = ["amqp","rabbitmq","protocol"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"

[lib]
name = "amq_protocol_codegen"

[dependencies]
amq-protocol-types = "^0.6.0"
itertools          = "^0.5.9"
serde              = "^0.9.11"
serde_derive       = "^0.9.11"
serde_json         = "^0.9.9"

[dependencies.handlebars]
version  = "^0.25.1"
features = ["serde_type"]

[badges]
travis-ci = { repository = "Keruspe/amq-protocol" }
