[package]
name          = "amq-protocol"
version       = "1.1.0" # remember to update html_root_url
edition       = "2018"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP specifications"
repository    = "https://github.com/sozu-proxy/amq-protocol"
documentation = "https://docs.rs/amq-protocol"
keywords      = ["amqp","rabbitmq","protocol","nom"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"
build         = "build.rs"

[lib]
name = "amq_protocol"

[build-dependencies.amq-protocol-codegen]
version = "^1.1"
path    = "../codegen"

[dependencies]
cookie-factory = "^0.2.4"
nom            = "^4.0"
url            = "^1.5"

[dependencies.amq-protocol-codegen]
version = "^1.1"
path    = "../codegen"

[dependencies.amq-protocol-types]
version = "^1.1"
path    = "../types"

[badges]
travis-ci = { repository = "sozu-proxy/amq-protocol" }
appveyor  = { repository = "Keruspe/amq-protocol" }
