[package]
name          = "amq-protocol"
version       = "6.0.0-beta2" # remember to update html_root_url
edition       = "2018"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP specifications"
repository    = "https://github.com/CleverCloud/amq-protocol"
documentation = "https://docs.rs/amq-protocol"
keywords      = ["amqp","rabbitmq","protocol","nom"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"
build         = "build.rs"

[lib]
name = "amq_protocol"

[features]
default                   = ["native-tls"]
native-tls                = ["amq-protocol-tcp/native-tls"]
openssl                   = ["amq-protocol-tcp/openssl"]
rustls                    = ["amq-protocol-tcp/rustls"]
rustls-native-certs       = ["amq-protocol-tcp/rustls-native-certs"]
rustls-webpki-roots-certs = ["amq-protocol-tcp/rustls-webpki-roots-certs"]
verbose-errors            = ["amq-protocol-types/verbose-errors"]

[build-dependencies.amq-protocol-codegen]
version = "=6.0.0-beta2"
path    = "../codegen"

[dependencies]
cookie-factory = "^0.3"

[dependencies.amq-protocol-tcp]
version          = "=6.0.0-beta2"
default-features = false
path             = "../tcp"

[dependencies.amq-protocol-types]
version = "=6.0.0-beta2"
path    = "../types"

[dependencies.amq-protocol-uri]
version = "=6.0.0-beta2"
path    = "../uri"

[dependencies.nom]
version  = "=6.0.0-alpha1"
features = ["std"]

[badges]
travis-ci = { repository = "sozu-proxy/amq-protocol" }
appveyor  = { repository = "Keruspe/amq-protocol" }
