[package]
name          = "amq-protocol"
version       = "0.6.0"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP specifications"
repository    = "https://github.com/Keruspe/amq-protocol"
documentation = "https://docs.rs/amq-protocol"
keywords      = ["amqp","rabbitmq","protocol"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"
build         = "build.rs"

[lib]
name = "amq_protocol"

[build-dependencies]
amq-protocol-codegen = "^0.16.0"

[dependencies]
amq-protocol-codegen = "^0.16.0"
amq-protocol-types   = "^0.9.0"

[badges]
travis-ci = { repository = "Keruspe/amq-protocol" }
