[package]
name          = "amq-protocol"
version       = "4.2.1" # remember to update html_root_url
edition       = "2018"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP specifications"
repository    = "https://github.com/sozu-proxy/amq-protocol"
documentation = "https://docs.rs/amq-protocol"
keywords      = ["amqp","rabbitmq","protocol","nom"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"
build         = "build.rs"

[lib]
name = "amq_protocol"

[features]
default             = ["native-tls"]
native-tls          = ["amq-protocol-tcp/native-tls"]
openssl             = ["amq-protocol-tcp/openssl"]
rustls              = ["amq-protocol-tcp/rustls"]
rustls-native-certs = ["amq-protocol-tcp/rustls-native-certs"]
verbose-errors      = ["amq-protocol-types/verbose-errors"]

[build-dependencies.amq-protocol-codegen]
version = "=4.2.1"
path    = "../codegen"

[dependencies]
cookie-factory = "^0.3"
nom            = "^5.0"

[dependencies.amq-protocol-tcp]
version          = "=4.2.1"
default-features = false
path             = "../tcp"

[dependencies.amq-protocol-types]
version = "=4.2.1"
path    = "../types"

[dependencies.amq-protocol-uri]
version = "=4.2.1"
path    = "../uri"

[badges]
travis-ci = { repository = "sozu-proxy/amq-protocol" }
appveyor  = { repository = "Keruspe/amq-protocol" }
