[package]
name          = "amq-protocol"
version       = "0.17.0"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP specifications"
repository    = "https://github.com/Keruspe/amq-protocol"
documentation = "https://docs.rs/amq-protocol"
keywords      = ["amqp","rabbitmq","protocol","nom"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"
build         = "build.rs"

[lib]
name = "amq_protocol"

[build-dependencies.amq-protocol-codegen]
version = "^0.26"
path    = "../codegen"

[dependencies]
cookie-factory = "^0.2.1"
nom            = "^3.0"
url            = "^1.4"

[dependencies.amq-protocol-codegen]
version = "^0.26"
path    = "../codegen"

[dependencies.amq-protocol-types]
version = "^0.19"
path    = "../types"

[badges]
travis-ci = { repository = "sozu-proxy/amq-protocol" }
appveyor  = { repository = "Keruspe/amq-protocol" }
