[package]
name          = "amq-protocol-tcp"
version       = "5.0.0-beta.2" # remember to update html_root_url
edition       = "2018"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP URI TCP connection handling"
repository    = "https://github.com/sozu-proxy/amq-protocol"
documentation = "https://docs.rs/amq-protocol-tcp"
keywords      = ["amqp","rabbitmq","protocol"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"

[lib]
name = "amq_protocol_tcp"

[features]
default                   = ["native-tls"]
native-tls                = ["tcp-stream/native-tls"]
openssl                   = ["tcp-stream/openssl"]
rustls                    = ["rustls-native-certs"]
rustls-native-certs       = ["tcp-stream/rustls-native-certs"]
rustls-webpki-roots-certs = ["tcp-stream/rustls-webpki-roots-certs"]
vendored                  = ["tcp-stream/vendored"]

[dependencies.amq-protocol-uri]
version = "=5.0.0-beta.2"
path    = "../uri"

[dependencies.mio]
version  = "^0.7"
features = ["os-poll"]

[dependencies.tcp-stream]
version          = "^0.10"
default-features = false

[badges]
travis-ci = { repository = "sozu-proxy/amq-protocol" }
appveyor  = { repository = "Keruspe/amq-protocol" }
